
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Darwin - 23.0.0 - arm64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: /Users/zaedinzeng/CLionProjects/llvm-project/build/bin/clang 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library not found for -lSystem
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /Users/zaedinzeng/CLionProjects/llvm-project/build/bin/clang 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/3.26.4-dirty/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
      Compiler: /Users/zaedinzeng/CLionProjects/llvm-project/build/bin/clang++ 
      Build flags: 
      Id flags:  
      
      The output was:
      1
      ld: library not found for -lc++
      clang++: error: linker command failed with exit code 1 (use -v to see invocation)
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /Users/zaedinzeng/CLionProjects/llvm-project/build/bin/clang++ 
      Build flags: 
      Id flags: -c 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/3.26.4-dirty/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/local/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-qUCd8y"
      binary: "/Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-qUCd8y"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: /Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-qUCd8y
        
        Run Build Command(s):/usr/local/bin/cmake -E env VERBOSE=1 /opt/homebrew/opt/llvm/bin/clang -f Makefile cmTC_3418f/fast && clang-16: error: unknown argument: '-f'
        clang-16: error: no such file or directory: 'cmTC_3418f/fast'
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/local/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: /Users/zaedinzeng/CLionProjects/llvm-project/build/bin/clang"
    directories:
      source: "/Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-dwHIPc"
      binary: "/Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-dwHIPc"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_OSX_ARCHITECTURES: ""
      CMAKE_OSX_DEPLOYMENT_TARGET: ""
      CMAKE_OSX_SYSROOT: "/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: /Users/zaedinzeng/CLionProjects/test/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-dwHIPc
        
        Run Build Command(s):/usr/local/bin/cmake -E env VERBOSE=1 /opt/homebrew/opt/llvm/bin/clang -f Makefile cmTC_f7f47/fast && clang-16: error: unknown argument: '-f'
        clang-16: error: no such file or directory: 'cmTC_f7f47/fast'
        
      exitCode: 1
...
